CREATE TABLE IF NOT EXISTS EMPLOYEE_DETAILS (
    ORG_NAME                VARCHAR(255) NOT NULL,
    NAME             VARCHAR(255) NOT NULL,
    DESIGNATION                VARCHAR(255) NOT NULL DEFAULT "Engineer",
    PRIMARY KEY (ORG_NAME, NAME, DESIGNATION)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;